apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "risk-ai-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "risk-ai-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "risk-ai-api.name" . }}
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
